#!/usr/bin/env python3
"""
ArmorIQ Documentation MCP Server

An MCP server that provides tools for searching and browsing
the ArmorIQ documentation (https://docs.armoriq.ai).
"""

import json
import re
import urllib.request
import urllib.error
from html.parser import HTMLParser
from mcp.server.fastmcp import FastMCP

# ---------------------------------------------------------------------------
# MCP server
# ---------------------------------------------------------------------------

mcp = FastMCP(
    "armoriq-docs",
    instructions="Search and browse ArmorIQ documentation — SDK, CLI, OpenClaw, integrations, and more.",
)

# ---------------------------------------------------------------------------
# Lightweight HTML → text helper
# ---------------------------------------------------------------------------

class _HTMLStripper(HTMLParser):
    """Minimal HTML-to-text converter."""

    def __init__(self):
        super().__init__()
        self._parts: list[str] = []
        self._skip = False

    def handle_starttag(self, tag, attrs):
        if tag in ("script", "style", "nav", "footer", "header"):
            self._skip = True
        if tag in ("p", "br", "div", "li", "h1", "h2", "h3", "h4", "tr"):
            self._parts.append("\n")

    def handle_endtag(self, tag):
        if tag in ("script", "style", "nav", "footer", "header"):
            self._skip = False

    def handle_data(self, data):
        if not self._skip:
            self._parts.append(data)

    def get_text(self) -> str:
        raw = "".join(self._parts)
        # collapse blank lines
        return re.sub(r"\n{3,}", "\n\n", raw).strip()


def _html_to_text(html: str) -> str:
    s = _HTMLStripper()
    s.feed(html)
    return s.get_text()


def _fetch(url: str, timeout: int = 15) -> str:
    """Fetch a URL and return the body text (HTML stripped)."""
    req = urllib.request.Request(url, headers={"User-Agent": "armoriq-docs-mcp/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        raw = resp.read().decode("utf-8", errors="replace")
    return _html_to_text(raw)


# ---------------------------------------------------------------------------
# Documentation index — pre-built from the site crawl
# ---------------------------------------------------------------------------

DOC_PAGES: dict[str, dict] = {
    # SDK docs
    "overview": {
        "title": "ArmorIQ SDK Overview",
        "url": "https://docs.armoriq.ai/docs",
        "summary": (
            "Build secure AI agents with cryptographic intent verification. "
            "One API key, per-request email scoping, framework-native adapters."
        ),
        "tags": ["sdk", "overview", "getting-started"],
    },
    "installation": {
        "title": "Installation",
        "url": "https://docs.armoriq.ai/docs/installation",
        "summary": (
            "Install the ArmorIQ SDK (Python: pip install armoriq-sdk, "
            "TypeScript: npm install @armoriq/sdk) and the armoriq CLI."
        ),
        "tags": ["install", "pip", "npm", "setup", "cli"],
    },
    "client-initialization": {
        "title": "Client Initialization",
        "url": "https://docs.armoriq.ai/docs/client-initialization",
        "summary": (
            "Initialize ArmorIQClient with an API key. Use client.for_user(email) "
            "to scope enforcement, tokens, and audit to a specific user."
        ),
        "tags": ["client", "init", "api-key", "for_user", "scope"],
    },
    "cli": {
        "title": "ArmorIQ CLI",
        "url": "https://docs.armoriq.ai/docs/cli",
        "summary": (
            "The armoriq CLI: init, login, logout, whoami, validate, register, "
            "status, logs, orgs, switch-org. Ships with pip install armoriq-sdk."
        ),
        "tags": ["cli", "armoriq", "init", "login", "validate", "register"],
    },
    "configuration": {
        "title": "Configuration",
        "url": "https://docs.armoriq.ai/docs/configuration",
        "summary": (
            "Configure via environment variables (ARMORIQ_API_KEY, ARMORIQ_ENV, etc.) "
            "or armoriq.yaml (generated by armoriq init). Full YAML schema reference."
        ),
        "tags": ["config", "yaml", "env", "environment", "armoriq.yaml", "proxy", "mcp_servers", "policy"],
    },
    "core-methods": {
        "title": "Core Methods",
        "url": "https://docs.armoriq.ai/docs/core-methods",
        "summary": "Overview of SDK core methods: capture_plan, get_intent_token, invoke, delegate.",
        "tags": ["methods", "api", "capture_plan", "get_intent_token", "invoke", "delegate"],
    },
    "capture-plan": {
        "title": "capture_plan()",
        "url": "https://docs.armoriq.ai/docs/core-methods/capture-plan",
        "summary": (
            "Capture and validate an execution plan. Accepts llm, prompt, plan (goal + steps), "
            "and optional metadata. Each step needs action, mcp, and optional params."
        ),
        "tags": ["capture_plan", "plan", "steps", "goal", "mcp", "action"],
    },
    "get-intent-token": {
        "title": "get_intent_token()",
        "url": "https://docs.armoriq.ai/docs/core-methods/get-intent-token",
        "summary": (
            "Request a cryptographically signed token from ArmorIQ. Accepts plan_capture, "
            "optional policy dict, and validity_seconds. Returns IntentToken."
        ),
        "tags": ["token", "intent", "csrg", "merkle", "ed25519", "policy"],
    },
    "invoke": {
        "title": "invoke()",
        "url": "https://docs.armoriq.ai/docs/core-methods/invoke",
        "summary": (
            "Execute an action on an MCP server with cryptographic verification. "
            "Sends Merkle proof via X-CSRG headers. Proxy verifies before routing to MCP."
        ),
        "tags": ["invoke", "execute", "mcp", "proxy", "csrg", "merkle", "verification"],
    },
    "delegate": {
        "title": "delegate()",
        "url": "https://docs.armoriq.ai/docs/core-methods/delegate",
        "summary": (
            "Delegate authority to a sub-agent with restricted permissions. "
            "Cryptographically bound, non-transferable, time-limited, action-restricted."
        ),
        "tags": ["delegate", "sub-agent", "authority", "permissions", "ed25519"],
    },
    "integrations": {
        "title": "Integrations",
        "url": "https://docs.armoriq.ai/docs/integrations",
        "summary": (
            "Framework adapters: Google ADK (Python) is live. CrewAI, LangChain, "
            "OpenAI, Anthropic, and all TypeScript adapters are on the roadmap."
        ),
        "tags": ["integrations", "google-adk", "crewai", "langchain", "openai", "anthropic", "adapter"],
    },
    "data-models": {
        "title": "Data Models",
        "url": "https://docs.armoriq.ai/docs/data-models",
        "summary": "Data model reference: IntentPlan, IntentToken, MCPResult.",
        "tags": ["models", "IntentPlan", "IntentToken", "MCPResult", "schema"],
    },
    "mcp-directory": {
        "title": "MCP Registry",
        "url": "https://docs.armoriq.ai/docs/mcp-directory",
        "summary": (
            "Register and manage MCP servers on the ArmorIQ platform. "
            "Login → MCP Registry → Add MCP (name + URL) → use in SDK."
        ),
        "tags": ["mcp", "registry", "register", "platform", "onboard"],
    },
    "error-handling": {
        "title": "Error Handling",
        "url": "https://docs.armoriq.ai/docs/error-handling",
        "summary": (
            "Error codes: AUTH_INVALID_KEY, AUTH_EXPIRED_KEY, TOKEN_EXPIRED, "
            "TOKEN_INVALID, VERIFICATION_FAILED, MERKLE_PROOF_INVALID, "
            "MCP_NOT_FOUND, ACTION_NOT_FOUND, INVALID_PARAMS, NETWORK_ERROR, "
            "TIMEOUT, RATE_LIMIT."
        ),
        "tags": ["errors", "error-codes", "troubleshooting", "exceptions"],
    },
    "advanced-usage": {
        "title": "Advanced Usage",
        "url": "https://docs.armoriq.ai/docs/advanced-usage",
        "summary": "Advanced topics: custom retry logic, connection pooling, token caching, batch invocation.",
        "tags": ["advanced", "retry", "pooling", "caching", "batch"],
    },
    "troubleshooting": {
        "title": "Troubleshooting",
        "url": "https://docs.armoriq.ai/docs/troubleshooting",
        "summary": (
            "Common issues: debug mode, invalid API key format, step verification failed, "
            "connection refused, token expired, performance profiling."
        ),
        "tags": ["troubleshooting", "debug", "errors", "performance"],
    },
    "best-practices": {
        "title": "Best Practices",
        "url": "https://docs.armoriq.ai/docs/best-practices",
        "summary": "SDK operation timings, client lifecycle management, singleton reuse.",
        "tags": ["best-practices", "performance", "lifecycle", "singleton"],
    },
    # OpenClaw / ArmorClaw docs
    "openclaw-getting-started": {
        "title": "Getting Started with ArmorClaw (OpenClaw)",
        "url": "https://docs-openclaw.armoriq.ai/docs",
        "summary": (
            "Set up OpenClaw AI assistant with ArmorClaw security plugin. "
            "Works in Telegram, Slack, Discord, WhatsApp. One-command install: "
            "curl -fsSL https://armoriq.ai/install-armorclaw.sh | bash"
        ),
        "tags": ["openclaw", "armorclaw", "telegram", "slack", "discord", "install", "gateway"],
    },
}


# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------


@mcp.tool()
def search_armoriq_docs(query: str) -> str:
    """Search the ArmorIQ documentation index.

    Finds relevant documentation pages by matching your query against
    page titles, summaries, and tags. Returns the top matches with
    titles, URLs, and summaries.

    Args:
        query: Natural-language search query (e.g. "how to install",
               "invoke method", "error codes", "OpenClaw setup").
    """
    query_lower = query.lower()
    tokens = set(re.findall(r"[a-z0-9_]+", query_lower))

    scored: list[tuple[float, str, dict]] = []
    for key, page in DOC_PAGES.items():
        score = 0.0
        haystack = f"{page['title']} {page['summary']} {' '.join(page['tags'])} {key}".lower()

        # exact substring match in haystack
        if query_lower in haystack:
            score += 10

        # token overlap
        for tok in tokens:
            if tok in haystack:
                score += 2
            # bonus for tag match
            if tok in [t.lower() for t in page["tags"]]:
                score += 3

        if score > 0:
            scored.append((score, key, page))

    scored.sort(key=lambda x: -x[0])
    top = scored[:8]

    if not top:
        return (
            "No matching documentation pages found. "
            "Try broader terms like 'sdk', 'cli', 'install', 'invoke', 'openclaw', 'errors'."
        )

    lines = [f"Found {len(top)} result(s) for \"{query}\":\n"]
    for _score, key, page in top:
        lines.append(f"### {page['title']}")
        lines.append(f"URL: {page['url']}")
        lines.append(f"{page['summary']}")
        lines.append(f"Tags: {', '.join(page['tags'])}")
        lines.append("")

    return "\n".join(lines)


@mcp.tool()
def get_armoriq_doc_page(page_id: str) -> str:
    """Fetch the full content of a specific ArmorIQ documentation page.

    Use search_armoriq_docs first to find the right page_id, then call
    this to get the complete page content fetched live from docs.armoriq.ai.

    Args:
        page_id: The page identifier. Valid values:
            overview, installation, client-initialization, cli,
            configuration, core-methods, capture-plan, get-intent-token,
            invoke, delegate, integrations, data-models, mcp-directory,
            error-handling, advanced-usage, troubleshooting, best-practices,
            openclaw-getting-started
    """
    page = DOC_PAGES.get(page_id)
    if not page:
        available = ", ".join(sorted(DOC_PAGES.keys()))
        return f"Unknown page_id '{page_id}'. Available pages: {available}"

    try:
        content = _fetch(page["url"])
    except Exception as exc:
        return f"Failed to fetch {page['url']}: {exc}"

    header = f"# {page['title']}\nSource: {page['url']}\n\n"
    return header + content


@mcp.tool()
def list_armoriq_doc_pages() -> str:
    """List all available ArmorIQ documentation pages.

    Returns every page in the index with its ID, title, and one-line summary.
    Use the page ID with get_armoriq_doc_page() to fetch full content.
    """
    lines = ["# ArmorIQ Documentation Index\n"]
    for key, page in DOC_PAGES.items():
        lines.append(f"- **{key}** — {page['title']}")
        lines.append(f"  {page['summary']}")
    return "\n".join(lines)


@mcp.tool()
def get_armoriq_quickstart() -> str:
    """Get a quick-start guide for the ArmorIQ SDK.

    Returns a condensed getting-started walkthrough covering installation,
    client setup, plan capture, token minting, and invocation — all in one shot.
    """
    return """\
# ArmorIQ SDK — Quick Start

## 1. Install
```bash
pip install armoriq-sdk          # Python
npm install @armoriq/sdk         # TypeScript
```

## 2. Authenticate (CLI — Python only today)
```bash
armoriq login      # browser-based OAuth
armoriq init       # scaffold armoriq.yaml
armoriq validate   # verify config + API key + MCPs
armoriq register   # push to control plane
```

## 3. Initialize the client
```python
from armoriq_sdk import ArmorIQClient

client = ArmorIQClient(api_key="ak_live_...")
scope  = client.for_user("alice@example.com")
```

## 4. Capture a plan
```python
plan = scope.capture_plan(
    llm="gpt-4",
    prompt="Fetch sales data and analyze trends",
    plan={
        "goal": "Retrieve and analyze sales data",
        "steps": [
            {"action": "fetch_sales", "mcp": "data-mcp", "params": {"quarter": "Q1"}},
            {"action": "analyze",     "mcp": "analytics-mcp", "params": {"type": "trends"}},
        ],
    },
)
```

## 5. Get an intent token
```python
token = scope.get_intent_token(plan_capture=plan)
```

## 6. Invoke actions (each verified cryptographically)
```python
result1 = scope.invoke(
    mcp="data-mcp",
    action="fetch_sales",
    intent_token=token,
    params={"quarter": "Q1"},
)

result2 = scope.invoke(
    mcp="analytics-mcp",
    action="analyze",
    intent_token=token,
    params={"type": "trends"},
)
```

## Key Concepts
- **One API key** — no user_id / agent_id to manage
- **for_user(email)** — scopes policies, audit, and tokens to a user
- **capture_plan()** → **get_intent_token()** → **invoke()** — the core flow
- **CSRG-IAP** — cryptographic plan hashing + Merkle proofs + Ed25519 signing
- **delegate()** — grant restricted, time-limited authority to sub-agents

## Environment Variables
```bash
export ARMORIQ_API_KEY="ak_live_..."
export ARMORIQ_ENV="production"        # or staging / local
export IAP_ENDPOINT="https://iap.armoriq.ai"
export PROXY_ENDPOINT="https://proxy.armoriq.ai"
export BACKEND_ENDPOINT="https://api.armoriq.ai"
```

## Error Codes
AUTH_INVALID_KEY, AUTH_EXPIRED_KEY, TOKEN_EXPIRED, TOKEN_INVALID,
VERIFICATION_FAILED, MERKLE_PROOF_INVALID, MCP_NOT_FOUND,
ACTION_NOT_FOUND, INVALID_PARAMS, NETWORK_ERROR, TIMEOUT, RATE_LIMIT

Full docs: https://docs.armoriq.ai
"""


@mcp.tool()
def get_armoriq_architecture() -> str:
    """Get the ArmorIQ platform architecture overview.

    Returns a description of how the ArmorIQ components fit together:
    SDK, Proxy, CSRG-IAP, Backend, and MCP servers.
    """
    return """\
# ArmorIQ Architecture

## Components

### SDK (Python / TypeScript)
- Client initialization with API key
- Per-user scoping via for_user(email)
- Plan capture, token minting, and verified invocation
- Framework adapters (Google ADK live; CrewAI, LangChain, OpenAI, Anthropic planned)

### ArmorIQ Proxy
- Receives invoke() calls from the SDK
- Validates API key (bcrypt)
- Forwards to CSRG-IAP for cryptographic verification
- Routes verified requests to the target MCP server
- Endpoint: https://proxy.armoriq.ai

### CSRG-IAP (Intent Access Proxy)
- Converts plans to Merkle tree structures
- Computes SHA-256 plan hashes
- Signs tokens with Ed25519
- Verifies step proofs on each invoke()
- Issues delegation tokens for sub-agents
- Endpoint: https://iap.armoriq.ai

### Backend Services
- Policy management and enforcement
- Audit logs and compliance tracking
- Organization and user management
- MCP Registry
- Endpoint: https://api.armoriq.ai

### MCP Servers (yours)
- Registered on platform.armoriq.ai → MCP Registry
- Each has a unique ID and HTTPS endpoint
- Auth: none, bearer token, or API key
- Actions are the tools your agent can call

## Request Flow
1. SDK: capture_plan() → validates plan structure
2. SDK: get_intent_token() → Proxy → CSRG-IAP mints token (plan_hash, merkle_root, step_proofs)
3. SDK: invoke() → Proxy verifies Merkle proof + Ed25519 signature → routes to MCP
4. MCP executes action → result returned through Proxy → SDK

## Security Headers (invoke)
- X-API-Key: authentication
- X-CSRG-Path: path in plan (e.g., /steps/[0]/action)
- X-CSRG-Value-Digest: SHA256 hash of action value
- X-CSRG-Proof: JSON Merkle proof array

## Delegation Flow
1. Parent agent gets intent token
2. Parent calls delegate() with delegate's Ed25519 public key
3. CSRG-IAP creates restricted, time-limited delegation token
4. Sub-agent uses delegated token for authorized actions only

Full docs: https://docs.armoriq.ai
"""


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    mcp.run()
